name: Processing Libraries
on: 
  push: 
    branches: [master]
jobs:
  nuget:
    runs-on: simple-kafka-raspberrypi
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build
      run: dotnet build -c Release
    - name: Pack
      run: dotnet pack
    - name: Publish
      run: dotnet nuget push .\nupkgs\*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://packages.gusmelford.com/v3/index.json --skip-duplicate
  notify:
    needs: [nuget]
    runs-on: simple-kafka-raspberrypi
    steps:
    - name: Send Telegram Notify
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "chat_id": "${{secrets.TELEGRAM_CHAT_STATUS}}",
            "text": " ${{ github.actor }} published TBot.
            
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            See changes: https://github.com/${{ github.repository }}/commit/${{github.sha}}"
          }' \
          https://api.telegram.org/bot${{secrets.TELEGRAM_TOKEN}}/sendMessage
